### ISSUE TITLE
Flashing text message with mkfifo error

### ISSUE THREAD

**Issue by chuwy** [luukvbaal/nnn.nvim#17] opened 2021-11-05 15:57 UTC
I'm getting following error message when I run my NeoVim:

```
mkfifo: cannot create file: /var/folders/k7/v1rr45_12xxb2w7jc9bxxv600000gp/T/nvimt20KFb/2-explorer
```

It flashes too fast, so perhaps there's something else. File already exists, its empty and nnn itself works without issues.

Disabling nnn.nvim helps (that's the only plugin I have that mentions mkfifo).

```
:version
NVIM v0.6.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by antonparkhomenko

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/nix/store/vw381ijplpsy50c80rgbk56fdxjbk53r-neovim-unwrapped-master/share/nvim"
```

```
$ mkfifo --version
mkfifo (GNU coreutils) 8.32
Packaged by https://NixOS.org
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David MacKenzie.
```

I run it on macOS with nix.

**Comment by luukvbaal** [comment] 2021-11-05 16:07
Are you on the latest commit? I recently pushed a fix for a similar error I was getting: https://github.com/luukvbaal/nnn.nvim/commit/ce89e2aaa70e20677e6d2b70a4bdb72485ff21c0.

Although the error looks a bit different on my system and only occurred when loading nnn.nvim when it is already loaded: `mkfifo: cannot create fifo '/run/user/1000/nvim4eRXtq/2-explorer': File exists`.

Are you seeing this error upon first load?

**Comment by chuwy** [comment] 2021-11-07 09:56
> Are you on the latest commit?

Pretty sure I was on the last one back when posted it.

In fact my error was the same (path is the one I mentioned, but `File exists` part is there).

> Are you seeing this error upon first load?

It appears right after I launch NeoVim (not `:Nnn...`). But then when I was debugging which plugin is causing that I was disabling plugins one by one and this message also appeared few times after `:PackerSync`.

**Comment by luukvbaal** [comment] 2021-11-07 10:56
> But then when I was debugging which plugin is causing that I was disabling plugins one by one and this message also appeared few times after `:PackerSync`.

Yes, this is how I noticed the error as well. Never seen it again since the fix from https://github.com/luukvbaal/nnn.nvim/commit/ce89e2aaa70e20677e6d2b70a4bdb72485ff21c0 though(can't think of how it would still occur). Please confirm whether it still happens on latest commit.

**Comment by luukvbaal** [comment] 2021-11-11 23:10
@chewy any update on this? Would like to know if you're still getting this error and if so, how to reproduce.

**Comment by luukvbaal** [comment] 2021-11-14 16:10
Closing this, feel free to reopen if you still encounter the issue.

**Closed by luukvbaal** 2021-11-14 16:10 UTC
